const countriesData = {
    "AD": { ru: "Андорра", en: "Andorra", pl: "Andora", it: "Andorra", de: "Andorra" },
    "AL": { ru: "Албания", en: "Albania", pl: "Albania", it: "Albania", de: "Albanien" },
    "AT": { ru: "Австрия", en: "Austria", pl: "Austria", it: "Austria", de: "Österreich" },
    "BA": { ru: "Босния и Герцеговина", en: "Bosnia and Herzegovina", pl: "Bośnia i Hercegowina", it: "Bosnia ed Erzegovina", de: "Bosnien und Herzegowina" },
    "BE": { ru: "Бельгия", en: "Belgium", pl: "Belgia", it: "Belgio", de: "Belgien" },
    "BG": { ru: "Болгария", en: "Bulgaria", pl: "Bułgaria", it: "Bulgaria", de: "Bulgarien" },
    "BY": { ru: "Беларусь", en: "Belarus", pl: "Białoruś", it: "Bielorussia", de: "Belarus" },
    "CH": { ru: "Швейцария", en: "Switzerland", pl: "Szwajcaria", it: "Svizzera", de: "Schweiz" },
    "CZ": { ru: "Чехия", en: "Czechia", pl: "Czechy", it: "Cechia", de: "Tschechien" },
    "DE": { ru: "Германия", en: "Germany", pl: "Niemcy", it: "Germania", de: "Deutschland" },
    "DK": { ru: "Дания", en: "Denmark", pl: "Dania", it: "Danimarca", de: "Dänemark" },
    "EE": { ru: "Эстония", en: "Estonia", pl: "Estonia", it: "Estonia", de: "Estland" },
    "ES": { ru: "Испания", en: "Spain", pl: "Hiszpania", it: "Spagna", de: "Spanien" },
    "FI": { ru: "Финляндия", en: "Finland", pl: "Finlandia", it: "Finlandia", de: "Finnland" },
    "FR": { ru: "Франция", en: "France", pl: "Francja", it: "Francia", de: "Frankreich" },
    "GB": { ru: "Великобритания", en: "United Kingdom", pl: "Wielka Brytania", it: "Regno Unito", de: "Vereinigtes Königreich" },
    "GR": { ru: "Греция", en: "Greece", pl: "Grecja", it: "Grecia", de: "Griechenland" },
    "HR": { ru: "Хорватия", en: "Croatia", pl: "Chorwacja", it: "Croazia", de: "Kroatien" },
    "HU": { ru: "Венгрия", en: "Hungary", pl: "Węgry", it: "Ungheria", de: "Ungarn" },
    "IE": { ru: "Ирландия", en: "Ireland", pl: "Irlandia", it: "Irlanda", de: "Irland" },
    "IS": { ru: "Исландия", en: "Iceland", pl: "Islandia", it: "Islanda", de: "Island" },
    "IT": { ru: "Италия", en: "Italy", pl: "Włochy", it: "Italia", de: "Italien" },
    "KZ": { ru: "Казахстан", en: "Kazakhstan", pl: "Kazachstan", it: "Kazakistan", de: "Kasachstan" },
    "LI": { ru: "Лихтенштейн", en: "Liechtenstein", pl: "Liechtenstein", it: "Liechtenstein", de: "Liechtenstein" },
    "LT": { ru: "Литва", en: "Lithuania", pl: "Litwa", it: "Lituania", de: "Litauen" },
    "LU": { ru: "Люксембург", en: "Luxembourg", pl: "Luksemburg", it: "Lussemburgo", de: "Luxemburg" },
    "LV": { ru: "Латвия", en: "Latvia", pl: "Łotwa", it: "Lettonia", de: "Lettland" },
    "MC": { ru: "Монако", en: "Monaco", pl: "Monako", it: "Monaco", de: "Monaco" },
    "MD": { ru: "Молдова", en: "Moldova", pl: "Mołdawia", it: "Moldavia", de: "Moldau" },
    "ME": { ru: "Черногория", en: "Montenegro", pl: "Czarnogóra", it: "Montenegro", de: "Montenegro" },
    "MK": { ru: "Северная Македония", en: "North Macedonia", pl: "Macedonia Północna", it: "Macedonia del Nord", de: "Nordmazedonien" },
    "MT": { ru: "Мальта", en: "Malta", pl: "Malta", it: "Malta", de: "Malta" },
    "NL": { ru: "Нидерланды", en: "Netherlands", pl: "Holandia", it: "Paesi Bassi", de: "Niederlande" },
    "NO": { ru: "Норвегия", en: "Norway", pl: "Norwegia", it: "Norvegia", de: "Norwegen" },
    "PL": { ru: "Польша", en: "Poland", pl: "Polska", it: "Polonia", de: "Polen" },
    "PT": { ru: "Португалия", en: "Portugal", pl: "Portugalia", it: "Portogallo", de: "Portugal" },
    "RO": { ru: "Румыния", en: "Romania", pl: "Rumunia", it: "Romania", de: "Rumänien" },
    "RS": { ru: "Сербия", en: "Serbia", pl: "Serbia", it: "Serbia", de: "Serbien" },
    "RU": { ru: "Российская Федерация", en: "Russian Federation", pl: "Federacja Rosyjska", it: "Federazione Russa", de: "Russische Föderation" },
    "SE": { ru: "Швеция", en: "Sweden", pl: "Szwecja", it: "Svezia", de: "Schweden" },
    "SI": { ru: "Словения", en: "Slovenia", pl: "Słowenia", it: "Slovenia", de: "Slowenien" },
    "SK": { ru: "Словакия", en: "Slovakia", pl: "Słowacja", it: "Slovacchia", de: "Slowakei" },
    "SM": { ru: "Сан-Марино", en: "San Marino", pl: "San Marino", it: "San Marino", de: "San Marino" },
    "UA": { ru: "Украина", en: "Ukraine", pl: "Ukraina", it: "Ucraina", de: "Ukraine" },
    "VA": { ru: "Ватикан", en: "Vatican City", pl: "Watykan", it: "Città del Vaticano", de: "Vatikanstadt" }
};


